language: android
android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-22

    # Additional components	
    - extra-android-support
    - extra-android-m2repository

    # Emulators for tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
	
before_install:
    - chmod +x gradlew